version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgres

volumes:
  db_volume: